### ISSUE TITLE
Epic - Farmers Market Search Endpoint

### ISSUE THREAD

**Issue by CoopTang** [CoopTang/market2table-be#7]
# Description
As a developer, I need to be able to query the [USDA Farmer's Market](https://search.ams.usda.gov/farmersmarkets/v1/svcdesc.html) API in order to get information on farmer's markets and then return a payload with the aggregated data.

## Requirements:
- [ ] #5 Farmer Markets API list
- [ ] #6 Farmer Market API details
- [ ] #8 Farmer Market Search Endpoint
